---
title: "Mixed GM for Microbiome and Metabolomic Data"
author: "Jing Ma"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---
  
  
```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = TRUE)

library(igraph)
library(fields)
library(ggplot2)
library(reshape2)
library(dplyr)
library(abind)
library(gridExtra)
library(mvtnorm)
library(MASS)
library(RANN)
library(cowplot)

source("lib/func_libs.R")
theme_set(theme_cowplot())

#---- ROC ----
get_roc <- function(path){
  filenames <- list.files(path)
  res <- lapply(paste0(path,filenames),function(a) {load(a);return(res)})
  
  rOracle <- apply(abind(lapply(1:length(res), function(j) data.frame('fp'=res[[j]]$oracle$fp,'tp'=res[[j]]$oracle$tp)), along=3),c(1,2),mean)
  rCensored <- apply(abind(lapply(1:length(res), function(j) data.frame('fp'=res[[j]]$direct$fp,'tp'=res[[j]]$direct$tp)), along=3),c(1,2),mean)
  rSpring <- apply(abind(lapply(1:length(res), function(j) data.frame('fp'=res[[j]]$spring$fp,'tp'=res[[j]]$spring$tp)), along=3),c(1,2),mean)
  rSpiec <- apply(abind(lapply(1:length(res), function(j) data.frame('fp'=res[[j]]$spiec$fp,'tp'=res[[j]]$spiec$tp)), along=3),c(1,2),mean)
  rmSpiec <- apply(abind(lapply(1:length(res), function(j) data.frame('fp'=res[[j]]$mspiec$fp,'tp'=res[[j]]$mspiec$tp)), along=3),c(1,2),mean)
  rgCoda <- apply(abind(lapply(1:length(res), function(j) data.frame('fp'=res[[j]]$gcoda$fp,'tp'=res[[j]]$gcoda$tp)), along=3),c(1,2),mean)
  
  df <- rbind(
    mutate(as.data.frame(rOracle),  'method'='Oracle'),
    mutate(as.data.frame(rCensored),'method'='metaMint'),
    # mutate(as.data.frame(rSpring),  'method'='SPRING'),
    mutate(as.data.frame(rgCoda),   'method'='gCoda'),
    mutate(as.data.frame(rSpiec),   'method'='SPIEC-EASI')) %>%
    mutate('method'=factor(method,c('Oracle','metaMint','SPRING','SPIEC-EASI','gCoda'))) 
  df
}

gg_color_hue <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}
my_cols <- gg_color_hue(5)
```

# ROC

```{r roc}
df <- rbind(mutate(get_roc("../Output/sfp60_v2/"),'network'='Scale-free'),
            mutate(get_roc("../Output/gnpp60_v2/"),'network'='Random'),
            mutate(get_roc("../Output/nnp60_v2/"),'network'='Nearest-Neighbor')) %>%
  mutate('network'=factor(network,c('Scale-free','Random','Nearest-Neighbor'))) 


p_roc <-  ggplot(df,aes(fp,tp,color=method)) +
  geom_line(aes(linetype=method)) + geom_point(aes(pch=method)) +
  facet_grid(.~network) +
  scale_linetype_manual(values=c("twodash", 'solid',"dotted",'dashed','dotdash')) +
  scale_shape_manual(values=c(17,16,18,8,9))+
  scale_colour_manual(values=my_cols[c(3,1,2,4,5)])+
  xlim(0,0.6) + ylim(0.4,1) + coord_fixed() +
  xlab("False positive rate") + ylab("True positive rate") #+ facet_wrap(pair~network,labeller = label_wrap_gen(multi_line=FALSE))
save_plot(p_roc,filename = '../Revision_R1/imgR1/roc_v1.png', base_asp = 2.5, base_height = 4)
print(p_roc)
```


## Graph topology

```{r topology}
# set.seed(2)
p = 100
g1 <- sample_pa(p, m=1, directed=FALSE)
V(g1)$color <- 'skyblue'
g2 <- hubNet(p,3)$g
V(g2)$color <- 'skyblue'
g3 <- nn.net(p,3)$g
V(g3)$color <- 'skyblue'
g4 <- sample_gnm(p,p,directed = FALSE)
V(g4)$color <- 'skyblue'
Amat <- as.matrix(get.adjacency(g4, type="both"))
E(g1)$color <- 'black'
E(g2)$color <- 'black'
E(g3)$color <- 'black'
E(g4)$color <- 'black'
E(g1)$weight <- 3
E(g3)$weight <- 3
E(g4)$weight <- 3
png(file='../Output/network_topology.png',width = 480*3*3, height = 480*3, units = "px",pointsize = 16)
par(mfrow=c(1,3),mar=rep(2,4))
plot(g1, vertex.size=5, vertex.label=NA,layout=layout_with_kk, edge.width = E(g1)$weight)
plot(g4, vertex.size=5, vertex.label=NA,edge.width = E(g4)$weight)
plot(g3, vertex.size=5, vertex.label=NA,edge.width = E(g3)$weight)
dev.off()
```

